USE ROLE SYSADMIN;

USE DATABASE DEMO_DEV;
USE SCHEMA RAW;

CREATE OR REPLACE STAGE DEV_STAGE
  COMMENT = 'Stage for DEV raw file ingestion';



USE ROLE SYSADMIN;

USE DATABASE DEMO_PRD;
USE SCHEMA RAW;

CREATE OR REPLACE STAGE PRD_STAGE
  COMMENT = 'Stage for PROD raw file ingestion';
