USE ROLE DEV_ROLE;
USE WAREHOUSE DEV_WH;
USE DATABASE DEMO_DEV;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE SUPERSTORE_RAW (
    ORDER_ID INT,
    ORDER_DATE DATE,
    SHIP_DATE DATE,
    ORDER_PRIORITY STRING,
    CUSTOMER_SEGMENT STRING,
    CUSTOMER_NAME STRING,
    SALES FLOAT,
    QUANTITY INT,
    PROFIT FLOAT,
    PROVINCE STRING,
    PRODUCT_CATEGORY STRING,
    PRODUCT_SUB_CATEGORY STRING,
    PRODUCT_NAME STRING
);