-- ========================
-- ✅ USE ADMIN
-- ========================
USE ROLE ACCOUNTADMIN;

-- ========================
-- ✅ CREATE ROLE
-- ========================
CREATE ROLE IF NOT EXISTS DEV_ROLE;
CREATE ROLE IF NOT EXISTS PRD_ROLE;

-- ========================
-- ✅ CREATE WAREHOUSE
-- ========================
CREATE WAREHOUSE IF NOT EXISTS DEV_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS PRD_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- ========================DEMO_PRD.RAW
-- ✅ CREATE DATABASE
-- ========================
CREATE DATABASE IF NOT EXISTS DEMO_DEV;
CREATE DATABASE IF NOT EXISTS DEMO_PRD;

-- ========================
-- ✅ CREATE SCHEMA
-- ========================
CREATE SCHEMA IF NOT EXISTS DEMO_DEV.RAW;
CREATE SCHEMA IF NOT EXISTS DEMO_PRD.RAW;

-- ========================
-- ✅ CREATE STAGE
-- ========================
CREATE STAGE IF NOT EXISTS DEMO_DEV.RAW.DEV_STAGE;
CREATE STAGE IF NOT EXISTS DEMO_PRD.RAW.PRD_STAGE;

-- ========================
-- ✅ GRANT: DEV
-- ========================
GRANT USAGE ON WAREHOUSE DEV_WH TO ROLE DEV_ROLE;

GRANT USAGE ON DATABASE DEMO_DEV TO ROLE DEV_ROLE;
GRANT USAGE ON SCHEMA DEMO_DEV.RAW TO ROLE DEV_ROLE;

GRANT CREATE TABLE ON SCHEMA DEMO_DEV.RAW TO ROLE DEV_ROLE;
GRANT CREATE STAGE ON SCHEMA DEMO_DEV.RAW TO ROLE DEV_ROLE;


GRANT READ, WRITE ON STAGE DEMO_DEV.RAW.DEV_STAGE TO ROLE DEV_ROLE;

-- future proof ✅
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA DEMO_DEV.RAW TO ROLE DEV_ROLE;

-- ========================
-- ✅ GRANT: PRD
-- ========================
GRANT USAGE ON WAREHOUSE PRD_WH TO ROLE PRD_ROLE;

GRANT USAGE ON DATABASE DEMO_PRD TO ROLE PRD_ROLE;
GRANT USAGE ON SCHEMA DEMO_PRD.RAW TO ROLE PRD_ROLE;

GRANT CREATE TABLE ON SCHEMA DEMO_PRD.RAW TO ROLE PRD_ROLE;

GRANT READ, WRITE ON STAGE DEMO_PRD.RAW.PRD_STAGE TO ROLE PRD_ROLE;

-- future proof ✅
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA DEMO_PRD.RAW TO ROLE PRD_ROLE;

-- ========================
-- ✅ ASSIGN ROLE TO USER
-- ========================
GRANT ROLE DEV_ROLE TO USER APHISIT;
GRANT ROLE PRD_ROLE TO USER APHISIT;

-- ========================
-- ✅ OPTIONAL (ทำให้ใช้ง่าย)
-- ========================
-- ตั้ง default role ให้ user (optional)
ALTER USER APHISIT SET DEFAULT_ROLE = DEV_ROLE;

-- ========================
-- ✅ USE ADMIN
-- ========================
USE ROLE ACCOUNTADMIN;

-- ========================
-- ✅ CREATE SCHEMA: SILVER
-- ========================
CREATE SCHEMA IF NOT EXISTS DEMO_DEV.SILVER;
CREATE SCHEMA IF NOT EXISTS DEMO_PRD.SILVER;

-- ========================
-- ✅ GRANT: DEV SILVER
-- ========================
GRANT USAGE ON SCHEMA DEMO_DEV.SILVER TO ROLE DEV_ROLE;
GRANT CREATE TABLE ON SCHEMA DEMO_DEV.SILVER TO ROLE DEV_ROLE;
-- future proof ✅
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA DEMO_DEV.SILVER TO ROLE DEV_ROLE;

-- ========================
-- ✅ GRANT: PRD SILVER
-- ========================
GRANT USAGE ON SCHEMA DEMO_PRD.SILVER TO ROLE PRD_ROLE;
GRANT CREATE TABLE ON SCHEMA DEMO_PRD.SILVER TO ROLE PRD_ROLE;
-- future proof ✅
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA DEMO_PRD.SILVER TO ROLE PRD_ROLE;

-- ========================
-- ✅ CREATE SCHEMA: GOLD
-- ========================
CREATE SCHEMA IF NOT EXISTS DEMO_DEV.GOLD;
CREATE SCHEMA IF NOT EXISTS DEMO_PRD.GOLD;

-- ========================
-- ✅ GRANT: DEV GOLD
-- ========================
GRANT USAGE ON SCHEMA DEMO_DEV.GOLD TO ROLE DEV_ROLE;
GRANT CREATE TABLE ON SCHEMA DEMO_DEV.GOLD TO ROLE DEV_ROLE;
-- future proof ✅
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA DEMO_DEV.GOLD TO ROLE DEV_ROLE;

-- ========================
-- ✅ GRANT: PRD GOLD
-- ========================
GRANT USAGE ON SCHEMA DEMO_PRD.GOLD TO ROLE PRD_ROLE;
GRANT CREATE TABLE ON SCHEMA DEMO_PRD.GOLD TO ROLE PRD_ROLE;
-- future proof ✅
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA DEMO_PRD.GOLD TO ROLE PRD_ROLE;