-- ================================
-- ✅ ใช้ SYSADMIN ทั้งหมด
-- ================================
USE ROLE SYSADMIN;

-- ================================
-- ✅ CREATE ROLE
-- ================================
CREATE ROLE IF NOT EXISTS DEV_ROLE;
CREATE ROLE IF NOT EXISTS PRD_ROLE;

-- ================================
-- ✅ CREATE WAREHOUSE
-- ================================
CREATE OR REPLACE WAREHOUSE DEV_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE WAREHOUSE PRD_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- ================================
-- ✅ CREATE DATABASE
-- ================================
CREATE OR REPLACE DATABASE DEMO_DEV;
CREATE OR REPLACE DATABASE DEMO_PRD;

-- ================================
-- ✅ CREATE SCHEMA
-- ================================

-- RAW
CREATE OR REPLACE SCHEMA DEMO_DEV.RAW;
CREATE OR REPLACE SCHEMA DEMO_PRD.RAW;

-- SILVER
CREATE OR REPLACE SCHEMA DEMO_DEV.SILVER;
CREATE OR REPLACE SCHEMA DEMO_PRD.SILVER;

-- GOLD
CREATE OR REPLACE SCHEMA DEMO_DEV.GOLD;
CREATE OR REPLACE SCHEMA DEMO_PRD.GOLD;

-- ================================
-- ✅ CREATE STAGE
-- ================================
CREATE OR REPLACE STAGE DEMO_DEV.RAW.DEV_STAGE;
CREATE OR REPLACE STAGE DEMO_PRD.RAW.PRD_STAGE;

-- ================================
-- ✅ GRANT: DEV ROLE
-- ================================

-- Warehouse
GRANT USAGE, OPERATE ON WAREHOUSE DEV_WH TO ROLE DEV_ROLE;

-- Database / Schema
GRANT USAGE ON DATABASE DEMO_DEV TO ROLE DEV_ROLE;
GRANT USAGE ON SCHEMA DEMO_DEV.RAW TO ROLE DEV_ROLE;
GRANT USAGE ON SCHEMA DEMO_DEV.SILVER TO ROLE DEV_ROLE;
GRANT USAGE ON SCHEMA DEMO_DEV.GOLD TO ROLE DEV_ROLE;

-- CREATE objects (DEV ทำได้เต็มที่)
GRANT CREATE TABLE ON SCHEMA DEMO_DEV.RAW TO ROLE DEV_ROLE;
GRANT CREATE TABLE ON SCHEMA DEMO_DEV.SILVER TO ROLE DEV_ROLE;
GRANT CREATE TABLE ON SCHEMA DEMO_DEV.GOLD TO ROLE DEV_ROLE;

GRANT CREATE STAGE ON SCHEMA DEMO_DEV.RAW TO ROLE DEV_ROLE;

-- Stage access
GRANT USAGE ON STAGE DEMO_DEV.RAW.DEV_STAGE TO ROLE DEV_ROLE;
GRANT READ, WRITE ON STAGE DEMO_DEV.RAW.DEV_STAGE TO ROLE DEV_ROLE;

-- Future tables
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA DEMO_DEV.RAW TO ROLE DEV_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA DEMO_DEV.SILVER TO ROLE DEV_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA DEMO_DEV.GOLD TO ROLE DEV_ROLE;

-- ================================
-- ✅ GRANT: PRD ROLE (strict กว่า)
-- ================================

-- Warehouse
GRANT USAGE, OPERATE ON WAREHOUSE PRD_WH TO ROLE PRD_ROLE;

-- Database / Schema
GRANT USAGE ON DATABASE DEMO_PRD TO ROLE PRD_ROLE;
GRANT USAGE ON SCHEMA DEMO_PRD.RAW TO ROLE PRD_ROLE;
GRANT USAGE ON SCHEMA DEMO_PRD.SILVER TO ROLE PRD_ROLE;
GRANT USAGE ON SCHEMA DEMO_PRD.GOLD TO ROLE PRD_ROLE;

-- ✅ PRD ไม่ให้ CREATE TABLE (best practice)
GRANT SELECT ON ALL TABLES IN SCHEMA DEMO_PRD.RAW TO ROLE PRD_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DEMO_PRD.SILVER TO ROLE PRD_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DEMO_PRD.GOLD TO ROLE PRD_ROLE;

-- Future tables (read only)
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEMO_PRD.RAW TO ROLE PRD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEMO_PRD.SILVER TO ROLE PRD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEMO_PRD.GOLD TO ROLE PRD_ROLE;

-- Stage access
GRANT USAGE ON STAGE DEMO_PRD.RAW.PRD_STAGE TO ROLE PRD_ROLE;
GRANT READ, WRITE ON STAGE DEMO_PRD.RAW.PRD_STAGE TO ROLE PRD_ROLE;

-- ================================
-- ✅ ASSIGN ROLE TO USER
-- ================================
GRANT ROLE DEV_ROLE TO USER APHISIT;
GRANT ROLE PRD_ROLE TO USER APHISIT;

-- ================================
-- ✅ OPTIONAL (ตั้ง default role)
-- ================================
ALTER USER APHISIT SET DEFAULT_ROLE = DEV_ROLE;