-- Sync code ล่าสุดจาก Git
ALTER GIT REPOSITORY SANDBOX_DB.SECURITY.SNOWFLAKE_GIT_REPO FETCH;

-- Recreate notebook จาก Git source ล่าสุด
CREATE OR REPLACE NOTEBOOK DEMO_DEV.GOLD.RAW_TO_SILVER
    FROM '@SANDBOX_DB.SECURITY.SNOWFLAKE_GIT_REPO/branches/main/notebook/'
    MAIN_FILE = 'S01 - Raw to Silver.ipynb'
    QUERY_WAREHOUSE = DEV_WH;

ALTER NOTEBOOK DEMO_DEV.GOLD.RAW_TO_SILVER ADD LIVE VERSION FROM LAST;

-- Execute
EXECUTE NOTEBOOK DEMO_DEV.GOLD.RAW_TO_SILVER();
--EXECUTE NOTEBOOK FROM '@SANDBOX_DB.SECURITY.SNOWFLAKE_GIT_REPO/branches/main/notebook/'

-- ดูว่า Live Version ที่รันอยู่ มาจาก commit ไหน
SHOW VERSIONS IN NOTEBOOK DEMO_DEV.GOLD.RAW_TO_SILVER;