-- ═══ EVERY DEPLOY (ADF Script Activity) ═══
ALTER GIT REPOSITORY SANDBOX_DB.SECURITY.SNOWFLAKE_GIT_REPO FETCH;

REMOVE @DEMO_DEV.NOTEBOOK.S01_DEPLOY_STAGE;
COPY FILES INTO @DEMO_DEV.NOTEBOOK.S01_DEPLOY_STAGE
  FROM @SANDBOX_DB.SECURITY.SNOWFLAKE_GIT_REPO/branches/dev/;

ALTER NOTEBOOK PROJECT DEMO_DEV.NOTEBOOK.S01_RAW_TO_SILVER_PROJ
  ADD VERSION FROM '@DEMO_DEV.NOTEBOOK.S01_DEPLOY_STAGE';

EXECUTE NOTEBOOK PROJECT DEMO_DEV.NOTEBOOK.S01_RAW_TO_SILVER_PROJ
  MAIN_FILE = 'notebook/S01 - Raw to Silver.ipynb'
  COMPUTE_POOL = 'DEV_CPU_POOL'
  RUNTIME = 'V2.7-CPU-PY3.12'
  QUERY_WAREHOUSE = 'DEV_WH';