USE ROLE SYSADMIN;

-- Step 1: สร้าง NPO
CREATE OR REPLACE NOTEBOOK PROJECT DEMO_DEV.NOTEBOOK.S01_RAW_TO_SILVER_PROJ
  FROM 'snow://workspace/USER$.PUBLIC."bacrepo-snowflake-poc"/versions/head' --last snapshot ล่าสุดที่ publish/deploy แล้ว
  COMMENT = 'S01 Raw to Silver - DEV';

-- Step 2: รัน
EXECUTE NOTEBOOK PROJECT DEMO_DEV.NOTEBOOK.S01_RAW_TO_SILVER_PROJ
  MAIN_FILE = 'notebook/S01 - Raw to Silver.ipynb'
  COMPUTE_POOL = 'DEV_CPU_POOL'
  RUNTIME = 'V2.2-CPU-PY3.10'
  QUERY_WAREHOUSE = 'DEV_WH';

SHOW NOTEBOOK PROJECTS IN DATABASE DEMO_DEV;
SHOW COMPUTE POOLS;