-- 1. Sync โค้ดล่าสุดจาก Git
ALTER GIT REPOSITORY SANDBOX_DB.SECURITY.SNOWFLAKE_GIT_REPO FETCH;

-- 2. Commit Live Version ก่อน แล้ว Publish ใหม่จาก LAST
ALTER NOTEBOOK DEMO_DEV.GOLD.RAW_TO_SILVER COMMIT;
ALTER NOTEBOOK DEMO_DEV.GOLD.RAW_TO_SILVER ADD LIVE VERSION FROM LAST;

-- 3. รัน
EXECUTE NOTEBOOK DEMO_DEV.GOLD.RAW_TO_SILVER();

-- ดูว่า Live Version ที่รันอยู่ มาจาก commit ไหน
SHOW VERSIONS IN NOTEBOOK DEMO_DEV.GOLD.RAW_TO_SILVER;