-- Create RAW TABLE
EXECUTE IMMEDIATE FROM 
  '@SANDBOX_DB.SECURITY.SNOWFLAKE_GIT_REPO/branches/main/sql/sql-table/S01 - Create RAW TABLE.sql';

-- COPY INTO TABLE  
EXECUTE IMMEDIATE FROM 
  '@SANDBOX_DB.SECURITY.SNOWFLAKE_GIT_REPO/branches/main/sql/sql-table/S02 - COPY INTO TABLE.sql';

-- Raw to Silver
EXECUTE IMMEDIATE FROM 
  '@SANDBOX_DB.SECURITY.SNOWFLAKE_GIT_REPO/branches/main/sql/sql-table/S03 - Raw to Silver.sql';


-- ใช้ Role ที่มีสิทธิ์สูงพอก่อน
USE ROLE SYSADMIN;

-- Grant CREATE NOTEBOOK ให้ DEV_ROLE บน DEMO_DEV.GOLD
GRANT CREATE NOTEBOOK ON SCHEMA DEMO_DEV.GOLD TO ROLE DEV_ROLE;

-- Grant CREATE NOTEBOOK ให้ PRD_ROLE บน DEMO_PRD.GOLD  
GRANT CREATE NOTEBOOK ON SCHEMA DEMO_PRD.GOLD TO ROLE PRD_ROLE;

-- DEV
CREATE OR REPLACE NOTEBOOK DEMO_DEV.GOLD.RAW_TO_SILVER
    FROM '@SANDBOX_DB.SECURITY.SNOWFLAKE_GIT_REPO/branches/main/notebook/'
    MAIN_FILE = 'S01 - Raw to Silver.ipynb'
    QUERY_WAREHOUSE = DEV_WH;

-- PRD
CREATE OR REPLACE NOTEBOOK DEMO_PRD.GOLD.RAW_TO_SILVER
    FROM '@SANDBOX_DB.SECURITY.SNOWFLAKE_GIT_REPO/branches/main/notebook/'
    MAIN_FILE = 'S01 - Raw to Silver.ipynb'
    QUERY_WAREHOUSE = PRD_WH;

-- แต่ไม่ต้อง CREATE ใหม่ทุกครั้ง
-- CREATE ครั้งเดียวพอครับ หลังจากนั้นแค่:
sql-- Fetch sync จาก Git
ALTER GIT REPOSITORY SANDBOX_DB.SECURITY.SNOWFLAKE_GIT_REPO FETCH;

-- Execute ได้เลย (โค้ดล่าสุดจาก Git อัตโนมัติ)
EXECUTE NOTEBOOK DEMO_DEV.RAW.RAW_TO_SILVER();